/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login Access Token
         * @description 用户登录接口 (获取 Access Token)
         *     1. 验证邮箱和密码
         *     2. 生成 JWT Token
         */
        post: operations["login_access_token_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register User
         * @description 用户注册接口
         *     1. 检查邮箱是否已存在
         *     2. 创建新用户并加密密码
         *     3. 自动登录 (返回 Token)
         */
        post: operations["register_user_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Stocks
         * @description 股票搜索接口
         *     - 同时支持本地数据库模糊搜索和远程 API 实时搜索
         *     - 如果本地没搜到且开启了 remote=True，会尝试从第三方源抓取并同步到本地
         */
        get: operations["search_stocks_api_portfolio_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Portfolio Summary
         * @description 获取投资组合汇总数据 (Get Portfolio Summary)
         */
        get: operations["get_portfolio_summary_api_portfolio_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Portfolio
         * @description 获取当前用户的投资组合列表 (Fetch User Portfolio)
         *
         *     逻辑 (Logic)：
         *     1. 联表查询：Portfolio (持仓) -> MarketDataCache (行情缓存) -> Stock (基础资料)
         *     2. 若 refresh=True，则同步/异步触发全量实时刷新
         *     3. 循环计算盈亏比例、市值、未实现盈亏等前端展示字段
         */
        get: operations["get_portfolio_api_portfolio__get"];
        put?: never;
        /**
         * Add Portfolio Item
         * @description 添加或更新自选股/持仓
         */
        post: operations["add_portfolio_item_api_portfolio__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Portfolio Item
         * @description 从自选股中删除
         */
        delete: operations["delete_portfolio_item_api_portfolio__ticker__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/{ticker}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Stock Data
         * @description 针对单个股票的手动强制刷新接口 (支持极速模式)
         */
        post: operations["refresh_stock_data_api_portfolio__ticker__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/{ticker}/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stock News
         * @description 获取该股票在数据库中存储的最新新闻
         */
        get: operations["get_stock_news_api_portfolio__ticker__news_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Reorder Portfolio
         * @description 批量更新排序权重 (Batch update sort_order)
         */
        patch: operations["reorder_portfolio_api_portfolio_reorder_patch"];
        trace?: never;
    };
    "/api/stocks/{ticker}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stock History
         * @description 接口：获取股票的历史行情数据，专为 K 线图打造。
         */
        get: operations["get_stock_history_api_stocks__ticker__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stocks/refresh_all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh All Stocks
         * @description 接口：一键同步当前数据库中所有活跃股票的最新行情。
         */
        post: operations["refresh_all_stocks_api_stocks_refresh_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Portfolio Analysis
         * @description 获取最近的一次全量持仓健康分析 (非实时生成)
         */
        get: operations["get_portfolio_analysis_api_analysis_portfolio_get"];
        put?: never;
        /**
         * Analyze Portfolio
         * @description 全量持仓健康分析接口 (Portfolio Health Check)
         */
        post: operations["analyze_portfolio_api_analysis_portfolio_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Latest Analysis
         * @description 获取单支股票最新的分析记录（不触发新 AI 分析，仅查库）
         */
        get: operations["get_latest_analysis_api_analysis__ticker__get"];
        put?: never;
        /**
         * Analyze Stock
         * @description 股票分析接口 (核心业务逻辑)
         *     1. 检查用户权限/SaaS限制 (免费用户每日限额)
         *     2. 获取实时行情数据 (价格、技术指标)
         *     3. 获取相关新闻 (上下文)
         *     4. 获取用户持仓信息 (成本、盈亏)
         *     5. 调用 AI 模型生成投资建议
         */
        post: operations["analyze_stock_api_analysis__ticker__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/{ticker}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analysis History
         * @description 获取股票历史分析记录列表 (History of AI Analysis)
         */
        get: operations["get_analysis_history_api_analysis__ticker__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/macro/radar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Macro Radar
         * @description 获取宏观雷达热点，支持静默自动刷新
         */
        get: operations["get_macro_radar_api_macro_radar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/macro/cls_news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cls News
         * @description 获取数据库中持久化的最新全球快讯。
         *     逻辑：DB 优先，根据新鲜度自动触发后台更新。支持 refresh=True 强制刷新。
         */
        get: operations["get_cls_news_api_macro_cls_news_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Users Me */
        get: operations["read_users_me_api_user_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change Password */
        put: operations["change_password_api_user_password_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update User Settings */
        put: operations["update_user_settings_api_user_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/test-connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Ai Connection */
        post: operations["test_ai_connection_api_user_test_connection_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Notification History
         * @description 获取通知历史记录流
         */
        get: operations["get_notification_history_api_notifications_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paper-trading/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Simulated Trades
         * @description 获取所有的模拟交易 (Get all simulated trades)
         */
        get: operations["get_simulated_trades_api_paper_trading__get"];
        put?: never;
        /**
         * Create Simulated Trade
         * @description 一键加入模拟盘 (Join Paper Trading)
         */
        post: operations["create_simulated_trade_api_paper_trading__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description 健康检查接口：确保后端服务在线
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisResponse */
        AnalysisResponse: {
            /** Ticker */
            ticker: string;
            /** Analysis */
            analysis?: string | null;
            /** Sentiment Score */
            sentiment_score?: number | null;
            /** Summary Status */
            summary_status?: string | null;
            /** Risk Level */
            risk_level?: string | null;
            /** Technical Analysis */
            technical_analysis?: string | null;
            /** Fundamental News */
            fundamental_news?: string | null;
            /** Action Advice */
            action_advice?: string | null;
            /** Investment Horizon */
            investment_horizon?: string | null;
            /** Confidence Level */
            confidence_level?: number | null;
            /** Immediate Action */
            immediate_action?: string | null;
            /** Target Price */
            target_price?: number | null;
            /** Stop Loss Price */
            stop_loss_price?: number | null;
            /** Entry Zone */
            entry_zone?: string | null;
            /** Entry Price Low */
            entry_price_low?: number | null;
            /** Entry Price High */
            entry_price_high?: number | null;
            /** Rr Ratio */
            rr_ratio?: string | null;
            /**
             * Is Cached
             * @default false
             */
            is_cached: boolean;
            /** Model Used */
            model_used?: string | null;
            /** Created At */
            created_at?: string | null;
            /** History Price */
            history_price?: number | null;
            /** Max Drawdown */
            max_drawdown?: number | null;
            /** Max Favorable Excursion */
            max_favorable_excursion?: number | null;
            /** Scenario Tags */
            scenario_tags?: {
                [key: string]: unknown;
            }[] | null;
            /** Audit Notes */
            audit_notes?: string | null;
            /** Thought Process */
            thought_process?: {
                [key: string]: unknown;
            }[] | null;
        };
        /** ApiConfig */
        ApiConfig: {
            /** Api Key */
            api_key?: string | null;
            /** Base Url */
            base_url?: string | null;
        };
        /** Body_login_access_token_api_auth_login_post */
        Body_login_access_token_api_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NotificationHistorySchema */
        NotificationHistorySchema: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Card Payload */
            card_payload: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** OHLCVItem */
        OHLCVItem: {
            /** Time */
            time: string;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
            /** Volume */
            volume?: number | null;
            /** Rsi */
            rsi?: number | null;
            /** Macd */
            macd?: number | null;
            /** Macd Signal */
            macd_signal?: number | null;
            /** Macd Hist */
            macd_hist?: number | null;
            /** Bb Upper */
            bb_upper?: number | null;
            /** Bb Middle */
            bb_middle?: number | null;
            /** Bb Lower */
            bb_lower?: number | null;
        };
        /** PasswordChange */
        PasswordChange: {
            /** Old Password */
            old_password: string;
            /** New Password */
            new_password: string;
        };
        /** PortfolioAnalysisResponse */
        PortfolioAnalysisResponse: {
            /** Health Score */
            health_score: number;
            /** Risk Level */
            risk_level: string;
            /** Summary */
            summary: string;
            /** Diversification Analysis */
            diversification_analysis: string;
            /** Strategic Advice */
            strategic_advice: string;
            /** Top Risks */
            top_risks: string[];
            /** Top Opportunities */
            top_opportunities: string[];
            /** Detailed Report */
            detailed_report: string;
            /** Model Used */
            model_used?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PortfolioCreate */
        PortfolioCreate: {
            /** Ticker */
            ticker: string;
            /** Quantity */
            quantity: number;
            /** Avg Cost */
            avg_cost: number;
        };
        /** PortfolioItem */
        PortfolioItem: {
            /** Ticker */
            ticker: string;
            /** Name */
            name?: string | null;
            /** Quantity */
            quantity: number;
            /** Avg Cost */
            avg_cost: number;
            /**
             * Current Price
             * @default 0
             */
            current_price: number;
            /**
             * Market Value
             * @default 0
             */
            market_value: number;
            /**
             * Unrealized Pl
             * @default 0
             */
            unrealized_pl: number;
            /**
             * Pl Percent
             * @default 0
             */
            pl_percent: number;
            /** Last Updated */
            last_updated?: string | null;
            /** Sector */
            sector?: string | null;
            /** Industry */
            industry?: string | null;
            /** Market Cap */
            market_cap?: number | null;
            /** Pe Ratio */
            pe_ratio?: number | null;
            /** Forward Pe */
            forward_pe?: number | null;
            /** Eps */
            eps?: number | null;
            /** Dividend Yield */
            dividend_yield?: number | null;
            /** Beta */
            beta?: number | null;
            /** Fifty Two Week High */
            fifty_two_week_high?: number | null;
            /** Fifty Two Week Low */
            fifty_two_week_low?: number | null;
            /** Pe Percentile */
            pe_percentile?: number | null;
            /** Pb Percentile */
            pb_percentile?: number | null;
            /** Net Inflow */
            net_inflow?: number | null;
            /** Rsi 14 */
            rsi_14?: number | null;
            /** Ma 20 */
            ma_20?: number | null;
            /** Ma 50 */
            ma_50?: number | null;
            /** Ma 200 */
            ma_200?: number | null;
            /** Macd Val */
            macd_val?: number | null;
            /** Macd Signal */
            macd_signal?: number | null;
            /** Macd Hist */
            macd_hist?: number | null;
            /** Macd Hist Slope */
            macd_hist_slope?: number | null;
            /** Macd Cross */
            macd_cross?: string | null;
            /**
             * Macd Is New Cross
             * @default false
             */
            macd_is_new_cross: boolean;
            /** Bb Upper */
            bb_upper?: number | null;
            /** Bb Middle */
            bb_middle?: number | null;
            /** Bb Lower */
            bb_lower?: number | null;
            /** Atr 14 */
            atr_14?: number | null;
            /** K Line */
            k_line?: number | null;
            /** D Line */
            d_line?: number | null;
            /** J Line */
            j_line?: number | null;
            /** Volume Ma 20 */
            volume_ma_20?: number | null;
            /** Volume Ratio */
            volume_ratio?: number | null;
            /** Adx 14 */
            adx_14?: number | null;
            /** Pivot Point */
            pivot_point?: number | null;
            /** Resistance 1 */
            resistance_1?: number | null;
            /** Resistance 2 */
            resistance_2?: number | null;
            /** Support 1 */
            support_1?: number | null;
            /** Support 2 */
            support_2?: number | null;
            /** Risk Reward Ratio */
            risk_reward_ratio?: number | null;
            /**
             * Change Percent
             * @default 0
             */
            change_percent: number | null;
            /** Market Status */
            market_status?: string | null;
        };
        /** PortfolioSummary */
        PortfolioSummary: {
            /** Total Market Value */
            total_market_value: number;
            /** Total Unrealized Pl */
            total_unrealized_pl: number;
            /** Total Pl Percent */
            total_pl_percent: number;
            /** Day Change */
            day_change: number;
            /** Holdings */
            holdings: components["schemas"]["PortfolioItem"][];
            /** Sector Exposure */
            sector_exposure: components["schemas"]["SectorExposure"][];
        };
        /** SearchResult */
        SearchResult: {
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
        };
        /** SectorExposure */
        SectorExposure: {
            /** Sector */
            sector: string;
            /** Weight */
            weight: number;
            /** Value */
            value: number;
        };
        /** TestConnectionRequest */
        TestConnectionRequest: {
            /** Provider */
            provider: string;
            /** Api Key */
            api_key?: string | null;
            /** Base Url */
            base_url?: string | null;
        };
        /** TestConnectionResponse */
        TestConnectionResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "error";
            /** Message */
            message: string;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
        };
        /**
         * TradeStatus
         * @enum {string}
         */
        TradeStatus: "OPEN" | "CLOSED_PROFIT" | "CLOSED_LOSS" | "CLOSED_MANUAL";
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** UserProfile */
        UserProfile: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Membership Tier */
            membership_tier: string;
            /** Has Deepseek Key */
            has_deepseek_key: boolean;
            /** Has Siliconflow Key */
            has_siliconflow_key: boolean;
            /** Api Configs */
            api_configs?: {
                [key: string]: components["schemas"]["ApiConfig"];
            } | null;
            /** Fallback Enabled */
            fallback_enabled: boolean;
            /** Preferred Data Source */
            preferred_data_source: string;
            /** Preferred Ai Model */
            preferred_ai_model: string;
            /** Timezone */
            timezone: string;
            /** Theme */
            theme: string;
            /** Feishu Webhook Url */
            feishu_webhook_url?: string | null;
            /** Enable Price Alerts */
            enable_price_alerts: boolean;
            /** Enable Hourly Summary */
            enable_hourly_summary: boolean;
            /** Enable Daily Report */
            enable_daily_report: boolean;
            /** Enable Macro Alerts */
            enable_macro_alerts: boolean;
        };
        /** UserSettingsUpdate */
        UserSettingsUpdate: {
            /** Api Key Deepseek */
            api_key_deepseek?: string | null;
            /** Api Key Siliconflow */
            api_key_siliconflow?: string | null;
            /** Api Configs */
            api_configs?: {
                [key: string]: components["schemas"]["ApiConfig"];
            } | null;
            /** Fallback Enabled */
            fallback_enabled?: boolean | null;
            /** Preferred Data Source */
            preferred_data_source?: string | null;
            /** Preferred Ai Model */
            preferred_ai_model?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** Theme */
            theme?: string | null;
            /** Feishu Webhook Url */
            feishu_webhook_url?: string | null;
            /** Enable Price Alerts */
            enable_price_alerts?: boolean | null;
            /** Enable Hourly Summary */
            enable_hourly_summary?: boolean | null;
            /** Enable Daily Report */
            enable_daily_report?: boolean | null;
            /** Enable Macro Alerts */
            enable_macro_alerts?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_access_token_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_access_token_api_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_user_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_stocks_api_portfolio_search_get: {
        parameters: {
            query?: {
                query?: string;
                remote?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_summary_api_portfolio_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioSummary"];
                };
            };
        };
    };
    get_portfolio_api_portfolio__get: {
        parameters: {
            query?: {
                refresh?: boolean;
                price_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_portfolio_item_api_portfolio__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_portfolio_item_api_portfolio__ticker__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_stock_data_api_portfolio__ticker__refresh_post: {
        parameters: {
            query?: {
                price_only?: boolean;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stock_news_api_portfolio__ticker__news_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_portfolio_api_portfolio_reorder_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                }[];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stock_history_api_stocks__ticker__history_get: {
        parameters: {
            query?: {
                period?: string;
                interval?: string;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OHLCVItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_all_stocks_api_stocks_refresh_all_post: {
        parameters: {
            query?: {
                price_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_analysis_api_analysis_portfolio_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioAnalysisResponse"];
                };
            };
        };
    };
    analyze_portfolio_api_analysis_portfolio_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioAnalysisResponse"];
                };
            };
        };
    };
    get_latest_analysis_api_analysis__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_stock_api_analysis__ticker__post: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_history_api_analysis__ticker__history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_macro_radar_api_macro_radar_get: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cls_news_api_macro_cls_news_get: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_users_me_api_user_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
        };
    };
    change_password_api_user_password_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_settings_api_user_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_ai_connection_api_user_test_connection_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestConnectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestConnectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_notification_history_api_notifications_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationHistorySchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_simulated_trades_api_paper_trading__get: {
        parameters: {
            query?: {
                status?: components["schemas"]["TradeStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_simulated_trade_api_paper_trading__post: {
        parameters: {
            query: {
                ticker: string;
                entry_price: number;
                entry_reason: string;
                target_price?: number | null;
                stop_loss_price?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
