/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login Access Token
         * @description 用户登录接口 (获取 Access Token)
         *     1. 验证邮箱和密码
         *     2. 生成 JWT Token
         */
        post: operations["login_access_token_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register User
         * @description 用户注册接口
         *     1. 检查邮箱是否已存在
         *     2. 创建新用户并加密密码
         *     3. 自动登录 (返回 Token)
         */
        post: operations["register_user_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Stocks
         * @description 股票搜索接口
         *     - 同时支持本地数据库模糊搜索和远程 API 实时搜索
         *     - 如果本地没搜到且开启了 remote=True，会尝试从第三方源抓取并同步到本地
         */
        get: operations["search_stocks_api_portfolio_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Portfolio
         * @description 获取当前用户的投资组合列表
         *     - 使用 outerjoin 一次性查出持仓量、最新价、基本面和技术指标
         *     - 如果 refresh=True，会触发后台并行更新所有持仓的实时行情
         */
        get: operations["get_portfolio_api_portfolio__get"];
        put?: never;
        /**
         * Add Portfolio Item
         * @description 添加或更新自选股/持仓
         */
        post: operations["add_portfolio_item_api_portfolio__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Portfolio Item
         * @description 从自选股中删除
         */
        delete: operations["delete_portfolio_item_api_portfolio__ticker__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/{ticker}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Stock Data
         * @description 针对单个股票的手动强制刷新接口
         */
        post: operations["refresh_stock_data_api_portfolio__ticker__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/{ticker}/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stock News
         * @description 获取该股票在数据库中存储的最新新闻
         */
        get: operations["get_stock_news_api_portfolio__ticker__news_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Latest Analysis
         * @description 获取单支股票最新的分析记录（不触发新 AI 分析，仅查库）
         */
        get: operations["get_latest_analysis_api_analysis__ticker__get"];
        put?: never;
        /**
         * Analyze Stock
         * @description 股票分析接口 (核心业务逻辑)
         *     1. 检查用户权限/SaaS限制 (免费用户每日限额)
         *     2. 获取实时行情数据 (价格、技术指标)
         *     3. 获取相关新闻 (上下文)
         *     4. 获取用户持仓信息 (成本、盈亏)
         *     5. 调用 AI 模型生成投资建议
         */
        post: operations["analyze_stock_api_analysis__ticker__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Users Me */
        get: operations["read_users_me_api_user_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update User Settings */
        put: operations["update_user_settings_api_user_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisResponse */
        AnalysisResponse: {
            /** Ticker */
            ticker: string;
            /** Analysis */
            analysis?: string | null;
            /** Sentiment Score */
            sentiment_score?: number | null;
            /** Summary Status */
            summary_status?: string | null;
            /** Risk Level */
            risk_level?: string | null;
            /** Technical Analysis */
            technical_analysis?: string | null;
            /** Fundamental News */
            fundamental_news?: string | null;
            /** Action Advice */
            action_advice?: string | null;
            /** Investment Horizon */
            investment_horizon?: string | null;
            /** Confidence Level */
            confidence_level?: number | null;
            /** Immediate Action */
            immediate_action?: string | null;
            /** Target Price */
            target_price?: number | null;
            /** Stop Loss Price */
            stop_loss_price?: number | null;
            /**
             * Is Cached
             * @default false
             */
            is_cached: boolean;
            /** Model Used */
            model_used?: string | null;
            /** Created At */
            created_at?: string | null;
        };
        /** Body_login_access_token_api_auth_login_post */
        Body_login_access_token_api_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PortfolioCreate */
        PortfolioCreate: {
            /** Ticker */
            ticker: string;
            /** Quantity */
            quantity: number;
            /** Avg Cost */
            avg_cost: number;
        };
        /** PortfolioItem */
        PortfolioItem: {
            /** Ticker */
            ticker: string;
            /** Name */
            name?: string | null;
            /** Quantity */
            quantity: number;
            /** Avg Cost */
            avg_cost: number;
            /**
             * Current Price
             * @default 0
             */
            current_price: number;
            /**
             * Market Value
             * @default 0
             */
            market_value: number;
            /**
             * Unrealized Pl
             * @default 0
             */
            unrealized_pl: number;
            /**
             * Pl Percent
             * @default 0
             */
            pl_percent: number;
            /** Last Updated */
            last_updated?: string | null;
            /** Sector */
            sector?: string | null;
            /** Industry */
            industry?: string | null;
            /** Market Cap */
            market_cap?: number | null;
            /** Pe Ratio */
            pe_ratio?: number | null;
            /** Forward Pe */
            forward_pe?: number | null;
            /** Eps */
            eps?: number | null;
            /** Dividend Yield */
            dividend_yield?: number | null;
            /** Beta */
            beta?: number | null;
            /** Fifty Two Week High */
            fifty_two_week_high?: number | null;
            /** Fifty Two Week Low */
            fifty_two_week_low?: number | null;
            /** Rsi 14 */
            rsi_14?: number | null;
            /** Ma 20 */
            ma_20?: number | null;
            /** Ma 50 */
            ma_50?: number | null;
            /** Ma 200 */
            ma_200?: number | null;
            /** Macd Val */
            macd_val?: number | null;
            /** Macd Signal */
            macd_signal?: number | null;
            /** Macd Hist */
            macd_hist?: number | null;
            /** Macd Hist Slope */
            macd_hist_slope?: number | null;
            /** Bb Upper */
            bb_upper?: number | null;
            /** Bb Middle */
            bb_middle?: number | null;
            /** Bb Lower */
            bb_lower?: number | null;
            /** Atr 14 */
            atr_14?: number | null;
            /** K Line */
            k_line?: number | null;
            /** D Line */
            d_line?: number | null;
            /** J Line */
            j_line?: number | null;
            /** Volume Ma 20 */
            volume_ma_20?: number | null;
            /** Volume Ratio */
            volume_ratio?: number | null;
            /** Adx 14 */
            adx_14?: number | null;
            /** Pivot Point */
            pivot_point?: number | null;
            /** Resistance 1 */
            resistance_1?: number | null;
            /** Resistance 2 */
            resistance_2?: number | null;
            /** Support 1 */
            support_1?: number | null;
            /** Support 2 */
            support_2?: number | null;
            /**
             * Change Percent
             * @default 0
             */
            change_percent: number | null;
        };
        /** SearchResult */
        SearchResult: {
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** UserProfile */
        UserProfile: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Membership Tier */
            membership_tier: string;
            /** Has Gemini Key */
            has_gemini_key: boolean;
            /** Has Deepseek Key */
            has_deepseek_key: boolean;
            /** Has Siliconflow Key */
            has_siliconflow_key: boolean;
            /** Preferred Data Source */
            preferred_data_source: string;
            /** Preferred Ai Model */
            preferred_ai_model: string;
        };
        /** UserSettingsUpdate */
        UserSettingsUpdate: {
            /** Api Key Gemini */
            api_key_gemini?: string | null;
            /** Api Key Deepseek */
            api_key_deepseek?: string | null;
            /** Api Key Siliconflow */
            api_key_siliconflow?: string | null;
            /** Preferred Data Source */
            preferred_data_source?: string | null;
            /** Preferred Ai Model */
            preferred_ai_model?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_access_token_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_access_token_api_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_user_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_stocks_api_portfolio_search_get: {
        parameters: {
            query?: {
                query?: string;
                remote?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_api_portfolio__get: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_portfolio_item_api_portfolio__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_portfolio_item_api_portfolio__ticker__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_stock_data_api_portfolio__ticker__refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stock_news_api_portfolio__ticker__news_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_analysis_api_analysis__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_stock_api_analysis__ticker__post: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_users_me_api_user_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
        };
    };
    update_user_settings_api_user_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
