"""Sync schema with models

Revision ID: 052e88ccdfbf
Revises: 261c72d24d12
Create Date: 2026-02-19 11:39:45.254513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '052e88ccdfbf'
down_revision: Union[str, Sequence[str], None] = '261c72d24d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_reports', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('ticker',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('input_context_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('market_data_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('macd_val', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('macd_signal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('macd_hist', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bb_upper', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bb_middle', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bb_lower', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('atr_14', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('k_line', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('d_line', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('j_line', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('volume_ma_20', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('volume_ratio', sa.Float(), nullable=True))

    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('ticker',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('avg_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('unique_user_ticker'), type_='unique')
        batch_op.create_unique_constraint('unique_user_stock', ['user_id', 'ticker'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_stock', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('unique_user_ticker'), ['user_id', 'ticker'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('avg_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('ticker',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('market_data_cache', schema=None) as batch_op:
        batch_op.drop_column('volume_ratio')
        batch_op.drop_column('volume_ma_20')
        batch_op.drop_column('j_line')
        batch_op.drop_column('d_line')
        batch_op.drop_column('k_line')
        batch_op.drop_column('atr_14')
        batch_op.drop_column('bb_lower')
        batch_op.drop_column('bb_middle')
        batch_op.drop_column('bb_upper')
        batch_op.drop_column('macd_hist')
        batch_op.drop_column('macd_signal')
        batch_op.drop_column('macd_val')

    with op.batch_alter_table('analysis_reports', schema=None) as batch_op:
        batch_op.alter_column('input_context_snapshot',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('ticker',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
