"""create ai model config table

Revision ID: 0675c6d039e6
Revises: a234193f1ade
Create Date: 2026-02-13 15:05:57.632653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0675c6d039e6'
down_revision: Union[str, Sequence[str], None] = 'a234193f1ade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_model_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_model_configs_key'), 'ai_model_configs', ['key'], unique=True)
    
    # --- Seed Data ---
    import uuid
    from datetime import datetime
    
    seed_data = [
        {
            "id": str(uuid.uuid4()),
            "key": "deepseek-v3",
            "provider": "siliconflow",
            "model_id": "Pro/deepseek-ai/DeepSeek-V3.2",
            "is_active": True,
            "description": "DeepSeek V3 (SiliconFlow)",
            "created_at": datetime.utcnow(),
            "updated_at": datetime.utcnow()
        },
        {
            "id": str(uuid.uuid4()),
            "key": "deepseek-r1",
            "provider": "siliconflow",
            "model_id": "Pro/deepseek-ai/DeepSeek-R1",
            "is_active": True,
            "description": "DeepSeek R1 (SiliconFlow) - Reasoning",
            "created_at": datetime.utcnow(),
            "updated_at": datetime.utcnow()
        },
        {
            "id": str(uuid.uuid4()),
            "key": "qwen-3-vl-thinking",
            "provider": "siliconflow",
            "model_id": "Qwen/Qwen3-VL-235B-A22B-Thinking",
            "is_active": True,
            "description": "Qwen 3 VL Thinking (SiliconFlow) - Default",
            "created_at": datetime.utcnow(),
            "updated_at": datetime.utcnow()
        },
        {
            "id": str(uuid.uuid4()),
            "key": "gemini-1.5-flash",
            "provider": "gemini",
            "model_id": "gemini-1.5-flash",
            "is_active": True,
            "description": "Google Gemini 1.5 Flash",
            "created_at": datetime.utcnow(),
            "updated_at": datetime.utcnow()
        }
    ]
    
    op.bulk_insert(sa.table('ai_model_configs',
        sa.Column('id', sa.String()),
        sa.Column('key', sa.String()),
        sa.Column('provider', sa.String()),
        sa.Column('model_id', sa.String()),
        sa.Column('is_active', sa.Boolean()),
        sa.Column('description', sa.String()),
        sa.Column('created_at', sa.DateTime()),
        sa.Column('updated_at', sa.DateTime())
    ), seed_data)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_model_configs_key'), table_name='ai_model_configs')
    op.drop_table('ai_model_configs')
    # ### end Alembic commands ###
