"""add structured action fields

Revision ID: 15c8d26963f4
Revises: f3fe98d72c73
Create Date: 2026-02-07 13:17:31.163584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15c8d26963f4'
down_revision: Union[str, Sequence[str], None] = 'f3fe98d72c73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_reports', sa.Column('immediate_action', sa.String(), nullable=True))
    op.add_column('analysis_reports', sa.Column('target_price', sa.Float(), nullable=True))
    op.add_column('analysis_reports', sa.Column('stop_loss_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_reports', 'stop_loss_price')
    op.drop_column('analysis_reports', 'target_price')
    op.drop_column('analysis_reports', 'immediate_action')
    # ### end Alembic commands ###
