"""add user preferences table

Revision ID: 1a2b3c4d5e6f
Revises: f5f8d8c2b1aa
Create Date: 2026-04-07

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a2b3c4d5e6f'
down_revision: Union[str, None] = 'f5f8d8c2b1aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust ###
    op.create_table(
        'user_preferences',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('investment_profile', sa.String(), nullable=False, default='BALANCED'),
        sa.Column('preferred_markets', sa.String(), nullable=False, default='A_SHARE'),
        sa.Column('notification_frequency', sa.String(), nullable=False, default='REALTIME'),
        sa.Column('onboarding_completed', sa.Boolean(), nullable=False, default=False),
        sa.Column('risk_tolerance_score', sa.Integer(), nullable=False, default=5),
        sa.Column('investment_experience_years', sa.Integer(), nullable=False, default=0),
        sa.Column('target_annual_return', sa.Integer(), nullable=False, default=10),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id'),
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust ###
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
