"""add_siliconflow_and_ai_model_to_user

Revision ID: 221e2b34d133
Revises: 54477ba71d32
Create Date: 2026-02-04 15:20:18.398657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '221e2b34d133'
down_revision: Union[str, Sequence[str], None] = '54477ba71d32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key_siliconflow', sa.String(), nullable=True))
    op.add_column('users', sa.Column('preferred_ai_model', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_ai_model')
    op.drop_column('users', 'api_key_siliconflow')
    # ### end Alembic commands ###
