"""Initial migration

Revision ID: 261c72d24d12
Revises: 731ab4ae1248
Create Date: 2026-02-19 01:17:39.629008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '261c72d24d12'
down_revision: Union[str, Sequence[str], None] = '731ab4ae1248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_reports', 'entry_zone')
    op.drop_column('analysis_reports', 'technical_analysis')
    op.drop_column('analysis_reports', 'fundamental_news')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_reports', sa.Column('fundamental_news', sa.TEXT(), nullable=True))
    op.add_column('analysis_reports', sa.Column('technical_analysis', sa.TEXT(), nullable=True))
    op.add_column('analysis_reports', sa.Column('entry_zone', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
