"""add stock lists tables

Revision ID: 2b3c4d5e6f7a
Revises: 1a2b3c4d5e6f
Create Date: 2026-04-07

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b3c4d5e6f7a'
down_revision: Union[str, None] = '1a2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust ###
    op.create_table(
        'stock_lists',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('is_default', sa.Boolean(), nullable=False, default=False),
        sa.Column('is_public', sa.Boolean(), nullable=False, default=False),
        sa.Column('created_at', sa.DateTime(), nullable=False, default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.UniqueConstraint('user_id', 'name', name='uq_user_list_name'),
    )
    op.create_index(op.f('ix_stock_lists_user_id'), 'stock_lists', ['user_id'], unique=False)

    op.create_table(
        'stock_list_items',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('list_id', sa.String(), nullable=False),
        sa.Column('ticker', sa.String(length=20), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('added_at', sa.DateTime(), nullable=False, default=sa.func.now()),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['list_id'], ['stock_lists.id'], ondelete='CASCADE'),
        sa.UniqueConstraint('list_id', 'ticker', name='uq_list_ticker'),
    )
    op.create_index(op.f('ix_stock_list_items_list_id'), 'stock_list_items', ['list_id'], unique=False)
    op.create_index(op.f('ix_stock_list_items_ticker'), 'stock_list_items', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust ###
    op.drop_index(op.f('ix_stock_list_items_ticker'), table_name='stock_list_items')
    op.drop_index(op.f('ix_stock_list_items_list_id'), table_name='stock_list_items')
    op.drop_table('stock_list_items')
    op.drop_index(op.f('ix_stock_lists_user_id'), table_name='stock_lists')
    op.drop_table('stock_lists')
    # ### end Alembic commands ###
