"""add structured analysis fields

Revision ID: 33f174f249a3
Revises: 221e2b34d133
Create Date: 2026-02-07 00:29:14.983309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33f174f249a3'
down_revision: Union[str, Sequence[str], None] = '221e2b34d133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_reports', sa.Column('summary_status', sa.String(), nullable=True))
    op.add_column('analysis_reports', sa.Column('risk_level', sa.String(), nullable=True))
    op.add_column('analysis_reports', sa.Column('technical_analysis', sa.Text(), nullable=True))
    op.add_column('analysis_reports', sa.Column('fundamental_news', sa.Text(), nullable=True))
    op.add_column('analysis_reports', sa.Column('action_advice', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_reports', 'action_advice')
    op.drop_column('analysis_reports', 'fundamental_news')
    op.drop_column('analysis_reports', 'technical_analysis')
    op.drop_column('analysis_reports', 'risk_level')
    op.drop_column('analysis_reports', 'summary_status')
    # ### end Alembic commands ###
