"""Add macd_hist_slope

Revision ID: 38e85b151950
Revises: d24f18d20e95
Create Date: 2026-02-07 16:38:35.444484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38e85b151950'
down_revision: Union[str, Sequence[str], None] = 'd24f18d20e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_data_cache', sa.Column('macd_hist_slope', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_data_cache', 'macd_hist_slope')
    # ### end Alembic commands ###
