"""add_more_technical_indicators

Revision ID: 48d7355e90d6
Revises: 35a834f440ba
Create Date: 2026-01-20 22:25:29.355690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48d7355e90d6'
down_revision: Union[str, Sequence[str], None] = '35a834f440ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 已经在 baseline 中创建，此处跳过
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_data_cache', 'volume_ma_20')
    op.drop_column('market_data_cache', 'j_line')
    op.drop_column('market_data_cache', 'd_line')
    op.drop_column('market_data_cache', 'k_line')
    op.drop_column('market_data_cache', 'atr_14')
    op.drop_column('market_data_cache', 'bb_lower')
    op.drop_column('market_data_cache', 'bb_middle')
    op.drop_column('market_data_cache', 'bb_upper')
    # ### end Alembic commands ###
