"""add_more_technical_indicators

Revision ID: 48d7355e90d6
Revises: 35a834f440ba
Create Date: 2026-01-20 22:25:29.355690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48d7355e90d6'
down_revision: Union[str, Sequence[str], None] = '35a834f440ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_data_cache', sa.Column('bb_upper', sa.Float(), nullable=True))
    op.add_column('market_data_cache', sa.Column('bb_middle', sa.Float(), nullable=True))
    op.add_column('market_data_cache', sa.Column('bb_lower', sa.Float(), nullable=True))
    op.add_column('market_data_cache', sa.Column('atr_14', sa.Float(), nullable=True))
    op.add_column('market_data_cache', sa.Column('k_line', sa.Float(), nullable=True))
    op.add_column('market_data_cache', sa.Column('d_line', sa.Float(), nullable=True))
    op.add_column('market_data_cache', sa.Column('j_line', sa.Float(), nullable=True))
    op.add_column('market_data_cache', sa.Column('volume_ma_20', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_data_cache', 'volume_ma_20')
    op.drop_column('market_data_cache', 'j_line')
    op.drop_column('market_data_cache', 'd_line')
    op.drop_column('market_data_cache', 'k_line')
    op.drop_column('market_data_cache', 'atr_14')
    op.drop_column('market_data_cache', 'bb_lower')
    op.drop_column('market_data_cache', 'bb_middle')
    op.drop_column('market_data_cache', 'bb_upper')
    # ### end Alembic commands ###
