"""add_exchange_to_stock

Revision ID: 54477ba71d32
Revises: 90eb8cc09d0d
Create Date: 2026-01-21 10:43:07.954978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54477ba71d32'
down_revision: Union[str, Sequence[str], None] = '90eb8cc09d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 已经在 baseline 中创建，此处跳过
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'exchange')
    # ### end Alembic commands ###
