"""add macd_is_new_cross to market_data_cache

Revision ID: 5721829650f6
Revises: 9a4b2fb9b115
Create Date: 2026-02-11 10:09:37.563863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5721829650f6'
down_revision: Union[str, Sequence[str], None] = '9a4b2fb9b115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_data_cache', sa.Column('macd_is_new_cross', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_data_cache', 'macd_is_new_cross')
    # ### end Alembic commands ###
