"""restore_missing_tables

Revision ID: 622396190b6b
Revises: ebe47fa8f408
Create Date: 2026-03-22 21:59:41.246938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '622396190b6b'
down_revision: Union[str, Sequence[str], None] = 'ebe47fa8f408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if enum exists before creating table that uses it
    op.execute("DROP TYPE IF EXISTS tradestatus")
    
    op.create_table('simulated_trades',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED_PROFIT', 'CLOSED_LOSS', 'CLOSED_MANUAL', name='tradestatus'), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('entry_reason', sa.Text(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('stop_loss_price', sa.Float(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl_pct', sa.Float(), nullable=True),
    sa.Column('exit_date', sa.DateTime(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('realized_pnl_pct', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulated_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulated_trades_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulated_trades_ticker'), ['ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulated_trades_user_id'), ['user_id'], unique=False)

    op.create_table('trade_history_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trade_id', sa.String(), nullable=False),
    sa.Column('log_date', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('pnl_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['simulated_trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade_history_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_history_logs_trade_id'), ['trade_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_history_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_history_logs_trade_id'))

    op.drop_table('trade_history_logs')
    with op.batch_alter_table('simulated_trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulated_trades_user_id'))
        batch_op.drop_index(batch_op.f('ix_simulated_trades_ticker'))
        batch_op.drop_index(batch_op.f('ix_simulated_trades_status'))

    op.drop_table('simulated_trades')
    # ### end Alembic commands ###
