"""Add is_ai_strategy to MarketDataCache

Revision ID: 731ab4ae1248
Revises: 0675c6d039e6
Create Date: 2026-02-13 15:31:01.410603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '731ab4ae1248'
down_revision: Union[str, Sequence[str], None] = '0675c6d039e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_data_cache', sa.Column('is_ai_strategy', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_data_cache', 'is_ai_strategy')
    # ### end Alembic commands ###
