"""Add SimulatedTrade and TradeHistoryLog models

Revision ID: 877955ab3cd8
Revises: ea09323a6286
Create Date: 2026-03-08 18:32:07.881889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '877955ab3cd8'
down_revision: Union[str, Sequence[str], None] = 'ea09323a6286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_reports', schema=None) as batch_op:
        batch_op.alter_column('scenario_tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('thought_process',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_logs_ticker'), ['ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('stock_news', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_stock_news_ticker_link'), type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_news', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_stock_news_ticker_link'), ['ticker', 'link'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_ticker'))

    with op.batch_alter_table('analysis_reports', schema=None) as batch_op:
        batch_op.alter_column('thought_process',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('scenario_tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    # ### end Alembic commands ###
