"""Add SimulatedTrade and TradeHistoryLog models

Revision ID: 877955ab3cd8
Revises: ea09323a6286
Create Date: 2026-03-08 18:32:07.881889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '877955ab3cd8'
down_revision: Union[str, Sequence[str], None] = 'ea09323a6286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _get_column_names(table_name: str) -> set[str]:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return {column["name"] for column in inspector.get_columns(table_name)}


def _get_table_names() -> set[str]:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return set(inspector.get_table_names())


def upgrade() -> None:
    """Upgrade schema."""
    table_names = _get_table_names()
    analysis_report_columns = _get_column_names("analysis_reports")
    with op.batch_alter_table('analysis_reports', schema=None) as batch_op:
        if 'max_drawdown' not in analysis_report_columns:
            batch_op.add_column(sa.Column('max_drawdown', sa.Float(), nullable=True))
        if 'max_favorable_excursion' not in analysis_report_columns:
            batch_op.add_column(sa.Column('max_favorable_excursion', sa.Float(), nullable=True))
        if 'audit_notes' not in analysis_report_columns:
            batch_op.add_column(sa.Column('audit_notes', sa.Text(), nullable=True))
        if 'scenario_tags' not in analysis_report_columns:
            batch_op.add_column(sa.Column('scenario_tags', sa.JSON(), nullable=True))
        else:
            batch_op.alter_column(
                'scenario_tags',
                existing_type=postgresql.JSONB(astext_type=sa.Text()),
                type_=sa.JSON(),
                existing_nullable=True,
            )
        if 'thought_process' not in analysis_report_columns:
            batch_op.add_column(sa.Column('thought_process', sa.JSON(), nullable=True))
        else:
            batch_op.alter_column(
                'thought_process',
                existing_type=postgresql.JSONB(astext_type=sa.Text()),
                type_=sa.JSON(),
                existing_nullable=True,
            )

    if 'notification_logs' in table_names:
        with op.batch_alter_table('notification_logs', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_notification_logs_ticker'), ['ticker'], unique=False)
            batch_op.create_index(batch_op.f('ix_notification_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('stock_news', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_stock_news_ticker_link'), type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    table_names = _get_table_names()
    with op.batch_alter_table('stock_news', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_stock_news_ticker_link'), ['ticker', 'link'], postgresql_nulls_not_distinct=False)

    if 'notification_logs' in table_names:
        with op.batch_alter_table('notification_logs', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_notification_logs_user_id'))
            batch_op.drop_index(batch_op.f('ix_notification_logs_ticker'))

    with op.batch_alter_table('analysis_reports', schema=None) as batch_op:
        batch_op.alter_column('thought_process',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('scenario_tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    # ### end Alembic commands ###
