"""add_stock_news_table

Revision ID: 90eb8cc09d0d
Revises: 48d7355e90d6
Create Date: 2026-01-21 00:00:48.364426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90eb8cc09d0d'
down_revision: Union[str, Sequence[str], None] = '48d7355e90d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_news',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('publish_time', sa.DateTime(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_news_ticker'), 'stock_news', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_news_ticker'), table_name='stock_news')
    op.drop_table('stock_news')
    # ### end Alembic commands ###
