"""Restore missing analysis report columns

Revision ID: 93320b786a9b
Revises: 052e88ccdfbf
Create Date: 2026-02-19 12:01:30.753359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93320b786a9b'
down_revision: Union[str, Sequence[str], None] = '052e88ccdfbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('technical_analysis', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fundamental_news', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('entry_zone', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_reports', schema=None) as batch_op:
        batch_op.drop_column('entry_zone')
        batch_op.drop_column('fundamental_news')
        batch_op.drop_column('technical_analysis')

    # ### end Alembic commands ###
