"""add macd_cross to market_data_cache

Revision ID: 9a4b2fb9b115
Revises: b78d1acc5044
Create Date: 2026-02-10 16:22:11.946936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a4b2fb9b115'
down_revision: Union[str, Sequence[str], None] = 'b78d1acc5044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_data_cache', sa.Column('macd_cross', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_data_cache', 'macd_cross')
    # ### end Alembic commands ###
