"""Add risk_reward_ratio to MarketDataCache

Revision ID: a234193f1ade
Revises: 5721829650f6
Create Date: 2026-02-11 11:11:59.434033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a234193f1ade'
down_revision: Union[str, Sequence[str], None] = '5721829650f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_data_cache', sa.Column('risk_reward_ratio', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_data_cache', 'risk_reward_ratio')
    # ### end Alembic commands ###
