"""create_provider_configs_v4

Revision ID: ab4e342e4749
Revises: 14a91cdcc9c2
Create Date: 2026-03-15 23:21:01.032735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab4e342e4749'
down_revision: Union[str, Sequence[str], None] = '14a91cdcc9c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _get_table_names() -> set[str]:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return set(inspector.get_table_names())


def _get_column_names(table_name: str) -> set[str]:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return {column["name"] for column in inspector.get_columns(table_name)}


def _get_index_names(table_name: str) -> set[str]:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return {index["name"] for index in inspector.get_indexes(table_name)}


def upgrade() -> None:
    """Upgrade schema."""
    table_names = _get_table_names()

    if 'provider_configs' not in table_names:
        op.create_table('provider_configs',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('provider_key', sa.String(), nullable=False),
        sa.Column('display_name', sa.String(), nullable=False),
        sa.Column('base_url', sa.String(), nullable=False),
        sa.Column('api_key_env', sa.String(), nullable=False),
        sa.Column('priority', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('max_retries', sa.Integer(), nullable=True),
        sa.Column('timeout_seconds', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )

    provider_index_names = _get_index_names('provider_configs')
    provider_key_index_name = op.f('ix_provider_configs_provider_key')
    if provider_key_index_name not in provider_index_names:
        with op.batch_alter_table('provider_configs', schema=None) as batch_op:
            batch_op.create_index(provider_key_index_name, ['provider_key'], unique=True)

    if 'trade_history_logs' in table_names:
        trade_history_index_names = _get_index_names('trade_history_logs')
        trade_history_index_name = op.f('ix_trade_history_logs_trade_id')
        with op.batch_alter_table('trade_history_logs', schema=None) as batch_op:
            if trade_history_index_name in trade_history_index_names:
                batch_op.drop_index(trade_history_index_name)
        op.drop_table('trade_history_logs')

    if 'ai_model_configs' in table_names:
        ai_model_config_columns = _get_column_names('ai_model_configs')
        with op.batch_alter_table('ai_model_configs', schema=None) as batch_op:
            if 'name' in ai_model_config_columns:
                batch_op.drop_column('name')
            if 'api_key_env' in ai_model_config_columns:
                batch_op.drop_column('api_key_env')
            if 'base_url' in ai_model_config_columns:
                batch_op.drop_column('base_url')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_model_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_url', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('api_key_env', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))

    op.create_table('trade_history_logs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('trade_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('log_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('pnl_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('trade_history_logs_pkey'))
    )
    with op.batch_alter_table('trade_history_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_history_logs_trade_id'), ['trade_id'], unique=False)

    with op.batch_alter_table('provider_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_configs_provider_key'))

    op.drop_table('provider_configs')
    # ### end Alembic commands ###
