"""add_user_ai_configs

Revision ID: ae1b8335eea2
Revises: ab4e342e4749
Create Date: 2026-03-15 23:41:39.031025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae1b8335eea2'
down_revision: Union[str, Sequence[str], None] = 'ab4e342e4749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 获取数据库连接以检查表是否存在
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()
    
    # 必须先删除从表 trade_history_logs，因为它依赖主表 simulated_trades
    if 'trade_history_logs' in tables:
        with op.batch_alter_table('trade_history_logs', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_trade_history_logs_trade_id'))
        op.drop_table('trade_history_logs')
        
    if 'simulated_trades' in tables:
        with op.batch_alter_table('simulated_trades', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_simulated_trades_status'))
            batch_op.drop_index(batch_op.f('ix_simulated_trades_ticker'))
            batch_op.drop_index(batch_op.f('ix_simulated_trades_user_id'))
        op.drop_table('simulated_trades')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_configs', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('fallback_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('fallback_enabled')
        batch_op.drop_column('api_configs')

    op.create_table('trade_history_logs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('trade_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('log_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('pnl_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['simulated_trades.id'], name=op.f('trade_history_logs_trade_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('trade_history_logs_pkey'))
    )
    with op.batch_alter_table('trade_history_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_history_logs_trade_id'), ['trade_id'], unique=False)

    op.create_table('simulated_trades',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('OPEN', 'CLOSED_PROFIT', 'CLOSED_LOSS', 'CLOSED_MANUAL', name='tradestatus'), autoincrement=False, nullable=False),
    sa.Column('entry_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('entry_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('entry_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('target_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('stop_loss_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('current_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('unrealized_pnl_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('exit_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('exit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('realized_pnl_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('exit_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], name=op.f('simulated_trades_ticker_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('simulated_trades_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('simulated_trades_pkey'))
    )
    with op.batch_alter_table('simulated_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulated_trades_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulated_trades_ticker'), ['ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulated_trades_status'), ['status'], unique=False)

    # ### end Alembic commands ###
