"""add numeric entry prices

Revision ID: b78d1acc5044
Revises: f9886ac0c8b0
Create Date: 2026-02-08 12:12:23.830799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b78d1acc5044'
down_revision: Union[str, Sequence[str], None] = 'f9886ac0c8b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_reports', sa.Column('entry_price_low', sa.Float(), nullable=True))
    op.add_column('analysis_reports', sa.Column('entry_price_high', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_reports', 'entry_price_high')
    op.drop_column('analysis_reports', 'entry_price_low')
    # ### end Alembic commands ###
