"""Add ADX and Pivot indicators

Revision ID: d24f18d20e95
Revises: 15c8d26963f4
Create Date: 2026-02-07 15:21:54.691369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd24f18d20e95'
down_revision: Union[str, Sequence[str], None] = '15c8d26963f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_data_cache', sa.Column('adx_14', sa.Float(), nullable=True))
    op.add_column('market_data_cache', sa.Column('pivot_point', sa.Float(), nullable=True))
    op.add_column('market_data_cache', sa.Column('resistance_1', sa.Float(), nullable=True))
    op.add_column('market_data_cache', sa.Column('resistance_2', sa.Float(), nullable=True))
    op.add_column('market_data_cache', sa.Column('support_1', sa.Float(), nullable=True))
    op.add_column('market_data_cache', sa.Column('support_2', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_data_cache', 'support_2')
    op.drop_column('market_data_cache', 'support_1')
    op.drop_column('market_data_cache', 'resistance_2')
    op.drop_column('market_data_cache', 'resistance_1')
    op.drop_column('market_data_cache', 'pivot_point')
    op.drop_column('market_data_cache', 'adx_14')
    # ### end Alembic commands ###
