"""add_notifications_enabled_to_user

Revision ID: ebe47fa8f408
Revises: 2f4d6b8c9a10
Create Date: 2026-03-22 21:58:06.201527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ebe47fa8f408'
down_revision: Union[str, Sequence[str], None] = '2f4d6b8c9a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_history_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_history_logs_trade_id'))

    op.drop_table('trade_history_logs')
    
    with op.batch_alter_table('simulated_trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulated_trades_status'))
        batch_op.drop_index(batch_op.f('ix_simulated_trades_ticker'))
        batch_op.drop_index(batch_op.f('ix_simulated_trades_user_id'))

    op.drop_table('simulated_trades')
    
    with op.batch_alter_table('analysis_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_reports_ticker_scope_model_created'))
        batch_op.drop_index(batch_op.f('ix_analysis_reports_user_scope_created'))
        batch_op.create_index(batch_op.f('ix_analysis_reports_report_scope'), ['report_scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_reports_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_provider_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_provider_credentials_provider_key'))
        batch_op.drop_index(batch_op.f('idx_user_provider_credentials_user_id'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notifications_enabled', sa.Boolean(), nullable=True))
        batch_op.alter_column('fallback_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.drop_column('api_key_gemini')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key_gemini', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.alter_column('fallback_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.drop_column('notifications_enabled')

    with op.batch_alter_table('user_provider_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_provider_credentials_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_provider_credentials_provider_key'), ['provider_key'], unique=False)

    with op.batch_alter_table('analysis_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_reports_report_scope'))
        batch_op.create_index(batch_op.f('ix_analysis_reports_user_scope_created'), ['user_id', 'report_scope', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_reports_ticker_scope_model_created'), ['ticker', 'report_scope', 'model_used', 'created_at'], unique=False)

    op.create_table('simulated_trades',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('OPEN', 'CLOSED_PROFIT', 'CLOSED_LOSS', 'CLOSED_MANUAL', name='tradestatus'), autoincrement=False, nullable=False),
    sa.Column('entry_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('entry_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('entry_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('target_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('stop_loss_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('current_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('unrealized_pnl_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('exit_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('exit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('realized_pnl_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('exit_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], name=op.f('simulated_trades_ticker_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('simulated_trades_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('simulated_trades_pkey'))
    )
    with op.batch_alter_table('simulated_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulated_trades_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulated_trades_ticker'), ['ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulated_trades_status'), ['status'], unique=False)

    op.create_table('trade_history_logs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('trade_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('log_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('pnl_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['simulated_trades.id'], name=op.f('trade_history_logs_trade_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('trade_history_logs_pkey'))
    )
    with op.batch_alter_table('trade_history_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_history_logs_trade_id'), ['trade_id'], unique=False)

    # ### end Alembic commands ###
