"""add horizon and confidence

Revision ID: f3fe98d72c73
Revises: 33f174f249a3
Create Date: 2026-02-07 11:54:02.399093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3fe98d72c73'
down_revision: Union[str, Sequence[str], None] = '33f174f249a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_reports', sa.Column('investment_horizon', sa.String(), nullable=True))
    op.add_column('analysis_reports', sa.Column('confidence_level', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_reports', 'confidence_level')
    op.drop_column('analysis_reports', 'investment_horizon')
    # ### end Alembic commands ###
