"""add trade setup fields

Revision ID: f9886ac0c8b0
Revises: 38e85b151950
Create Date: 2026-02-07 22:35:07.255935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9886ac0c8b0'
down_revision: Union[str, Sequence[str], None] = '38e85b151950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_reports', sa.Column('entry_zone', sa.String(), nullable=True))
    op.add_column('analysis_reports', sa.Column('rr_ratio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_reports', 'rr_ratio')
    op.drop_column('analysis_reports', 'entry_zone')
    # ### end Alembic commands ###
